project-restricted-list:
  - gcp-labs-management

projects:
  "gcp-labs-xyo4pemi":
    presets:
      - "common"
    locations:
      - global
      - us-central1

presets:
  common:
    filters:
      Firewall:
        - property: Name
          type: glob
          value: "default-allow-*"
      Route:
        - property: Network
          value: "default"
      IAMServiceAccount:
        - property: Name
          type: glob
          value: "microsoft-defender*"
        - property: Name
          type: glob
          value: "*compute@developer*"
        - property: Name
          type: glob
          value: "*appspot*"
        - property: Name
          type: glob
          value: "*appengine-lab-1-target*"
      Bucket:
        - property: Name
          type: glob
          value: "*appspot*"
        - property: Name
          type: glob
          value: "*appengine-lab-1*"

resource-types:
  excludes:
